<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Binance\Binance.csproj" />
    <ProjectReference Include="..\CryptoTrading.App.Broker\CryptoTrading.App.Broker.csproj" />
    <ProjectReference Include="..\CryptoTrading.App.TradeMonitor\CryptoTrading.App.Monitor.csproj" />
  </ItemGroup>

</Project>
