<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0-preview.4.21253.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Binance\Binance.csproj" />
    <ProjectReference Include="..\CryptoTrading.App.Core\CryptoTrading.App.Core.csproj" />
    <ProjectReference Include="..\Indicators\Tulip.NETCore.csproj" />
  </ItemGroup>

</Project>
