<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoTrading.App.Algorthm\CryptoTrading.App.Algorthm.csproj" />
    <ProjectReference Include="..\CryptoTrading.App.Core\CryptoTrading.App.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="MarketDataTest.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
