// <auto-generated />
using System;
using CryptoTrading.App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoTrading.App.Persistence.Migrations
{
    [DbContext(typeof(CryptoDbContextPg))]
    [Migration("20260530194602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoTrading.App.Persistence.Entities.AlgoStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("instance_id");

                    b.Property<int>("Last1hBarCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_1h_bar_count");

                    b.Property<int>("Last4hBarCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_4h_bar_count");

                    b.Property<DateTime>("LastBarTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_bar_time");

                    b.Property<string>("StateJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("state_json");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strategy_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StrategyName", "InstanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_algo_state_strategy_instance");

                    b.ToTable("algo_state");
                });

            modelBuilder.Entity("CryptoTrading.App.Persistence.Entities.CandlestickEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Close")
                        .HasColumnType("double precision")
                        .HasColumnName("close");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("close_time");

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exchange_id");

                    b.Property<double>("High")
                        .HasColumnType("double precision")
                        .HasColumnName("high");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<double>("Low")
                        .HasColumnType("double precision")
                        .HasColumnName("low");

                    b.Property<long>("NumberOfTrades")
                        .HasColumnType("bigint")
                        .HasColumnName("number_of_trades");

                    b.Property<double>("Open")
                        .HasColumnType("double precision")
                        .HasColumnName("open");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("open_time");

                    b.Property<decimal>("QuoteVolume")
                        .HasColumnType("numeric")
                        .HasColumnName("quote_volume");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Interval", "OpenTime")
                        .HasDatabaseName("ix_candlesticks_symbol_interval_time");

                    b.HasIndex("ExchangeId", "Symbol", "Interval", "OpenTime")
                        .IsUnique()
                        .HasDatabaseName("ix_candlesticks_exchange_symbol_interval_time");

                    b.ToTable("candlesticks");
                });

            modelBuilder.Entity("CryptoTrading.App.Persistence.Entities.ExchangeConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("api_key");

                    b.Property<string>("ApiSecret")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("api_secret");

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exchange_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastRefreshed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refreshed");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<int>("RefreshIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_interval_minutes");

                    b.Property<string>("RunType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("run_type");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("ix_exchange_configs_exchange_id");

                    b.ToTable("exchange_configs");
                });

            modelBuilder.Entity("CryptoTrading.App.Persistence.Entities.ModelArtifactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ManifestJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("manifest_json");

                    b.Property<byte[]>("Model1hOnnx")
                        .HasColumnType("bytea")
                        .HasColumnName("model_1h_onnx");

                    b.Property<byte[]>("Model4hOnnx")
                        .HasColumnType("bytea")
                        .HasColumnName("model_4h_onnx");

                    b.Property<DateTime?>("PromotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promoted_at");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strategy_name");

                    b.Property<int>("TrainNBars")
                        .HasColumnType("integer")
                        .HasColumnName("train_n_bars");

                    b.Property<DateTime>("TrainedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trained_at");

                    b.Property<double>("ValR2_1h")
                        .HasColumnType("double precision")
                        .HasColumnName("val_r2_1h");

                    b.Property<double>("ValR2_4h")
                        .HasColumnType("double precision")
                        .HasColumnName("val_r2_4h");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("StrategyName", "IsActive")
                        .HasDatabaseName("ix_model_artifacts_strategy_active");

                    b.HasIndex("StrategyName", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_model_artifacts_strategy_version");

                    b.ToTable("model_artifacts");
                });

            modelBuilder.Entity("CryptoTrading.App.Persistence.Entities.StrategyParameterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parameter_name");

                    b.Property<int>("ParameterSetId")
                        .HasColumnType("integer")
                        .HasColumnName("parameter_set_id");

                    b.Property<double>("StepSize")
                        .HasColumnType("double precision")
                        .HasColumnName("step_size");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strategy_name");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("strategy_parameters");
                });

            modelBuilder.Entity("CryptoTrading.App.Persistence.Entities.TradeLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("EntryPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("entry_price");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_time");

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exchange_id");

                    b.Property<double>("ExitPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("exit_price");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_time");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<double>("Pnl")
                        .HasColumnType("double precision")
                        .HasColumnName("pnl");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("side");

                    b.Property<string>("SignalType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("signal_type");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strategy_name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("StrategyName", "Symbol", "EntryTime")
                        .HasDatabaseName("ix_trade_log_strategy_symbol_time");

                    b.ToTable("trade_log");
                });

            modelBuilder.Entity("CryptoTrading.App.Persistence.Entities.TradingPairEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExchangeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exchange_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ix_trading_pairs_exchange_symbol");

                    b.ToTable("trading_pairs");
                });
#pragma warning restore 612, 618
        }
    }
}
